

def hydrate(self, project_name):
    import ktk
    from pyspark.sql.functions import col, create_map, lit, col, crc32, concat
    from itertools import chain
    import json

    onb = ktk.OrchestrationDeltaNotebook()
    onb.displayAttributes()

    onb.create_orchestration_schema()

    onb.create_orchestration_staging_tables(project_name)

    system_name = 'UAT_SQL_adventureworkslt_ingest'
    stage_name = 'UAT_SQL_adventureworkslt_ingest_daily'
    system_secret_scope = 'adventureworkslt'
    system_order = 20
    stage_order = 10
    job_order = 10    

    #hydrate batch sql
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='SalesLT',table_name='SalesOrderHeader',primary_key_columns='SalesOrderID',timestamp_columns='DueDate,ModifiedDate,OrderDate,ShipDate')
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_dbo_BuildVersion',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='dbo',table_name='BuildVersion',primary_key_columns='SystemInformationID',timestamp_columns='VersionDate,ModifiedDate',load_type='Append',pushdown_query = 'SELECT * FROM dbo.BuildVersion WHERE 1=1 OR ModifiedDate >= DATEADD(DAY, -30, SYSDATETIME())')
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_SalesLT_ProductModel',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='SalesLT',table_name='ProductModel',primary_key_columns='ProductModelID',timestamp_columns='ModifiedDate', use_windowed_extraction = True, windowing_column = 'ModifiedDate', windowed_extraction_begin_date = '2002-01-01', windowed_extraction_end_date='2021-01-01', windowed_extraction_interval = 'Y', windowed_extraction_process_latest_window_first = False)
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_SalesLT_Address',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='SalesLT',table_name='Address',primary_key_columns='AddressID',timestamp_columns='ModifiedDate', silver_zone_partition_column = 'StateProvince', encrypt_columns = 'AddressLine1,AddressLine2', load_type = 'Overwrite', destination = 'silverprotected')
    onb.update_stage_threads(project_name=project_name, stage_name=stage_name, threads=4)

    stage_name = 'UAT_SQL_adventureworkslt_ingest_daily_rerun'
    stage_order = 20

    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader_rerun',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='SalesLT',table_name='SalesOrderHeader',primary_key_columns='SalesOrderID',timestamp_columns='DueDate,ModifiedDate,OrderDate,ShipDate')
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_dbo_BuildVersion_rerun',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='dbo',table_name='BuildVersion',primary_key_columns='SystemInformationID',timestamp_columns='VersionDate,ModifiedDate',load_type='Append',pushdown_query = 'SELECT * FROM dbo.BuildVersion WHERE 1=1 OR ModifiedDate >= DATEADD(DAY, -30, SYSDATETIME())')
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_SalesLT_Address_rerun',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='SalesLT',table_name='Address',primary_key_columns='AddressID',timestamp_columns='ModifiedDate', silver_zone_partition_column = 'StateProvince', encrypt_columns = 'AddressLine1,AddressLine2', load_type = 'Overwrite', destination = 'silverprotected')
    onb.update_stage_threads(project_name=project_name, stage_name=stage_name, threads=4)

    system_name = 'UAT_SQL_adventureworkslt_ingest_second_system'
    stage_name = 'UAT_SQL_adventureworkslt_ingest__second_system_daily'
    system_secret_scope = 'adventureworkslt'
    system_order = 30
    stage_order = 10
    job_order = 10

    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader_rerun2',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='SalesLT',table_name='SalesOrderHeader',primary_key_columns='SalesOrderID',timestamp_columns='DueDate,ModifiedDate,OrderDate,ShipDate')
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_dbo_BuildVersion_rerun2',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='dbo',table_name='BuildVersion',primary_key_columns='SystemInformationID',timestamp_columns='VersionDate,ModifiedDate',load_type='Append',pushdown_query = 'SELECT * FROM dbo.BuildVersion WHERE 1=1 OR ModifiedDate >= DATEADD(DAY, -30, SYSDATETIME())')
    onb.hydrate_batch_sql(project_name=project_name,system_name=system_name,stage_name=stage_name,job_name = 'UAT_SQL_adventureworkslt_SalesLT_Address_rerun2',system_secret_scope=system_secret_scope,system_order=system_order,stage_order=stage_order,job_order=job_order,schema_name='SalesLT',table_name='Address',primary_key_columns='AddressID',timestamp_columns='ModifiedDate', silver_zone_partition_column = 'StateProvince', encrypt_columns = 'AddressLine1,AddressLine2', load_type = 'Overwrite', destination = 'silverprotected')
    onb.update_stage_threads(project_name=project_name, stage_name=stage_name, threads=4)    

    #hydrate gold zone
    onb.hydrate_gold_zone(project_name='UAT_SQL',system_name='UAT_SQL_adventureworkslt_enrich',system_secret_scope='internal',system_is_active=True,system_order=30,stage_name='UAT_SQL_adventureworkslt_enrich_daily',stage_is_active=True,stage_order=20,job_name='UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader',job_is_active=True,job_order=10,view_name='silvergeneral.vadventureworkslt_saleslt_salesorderheader',table_name='goldgeneral.adventureworkslt_saleslt_salesorderheader',purpose='uatsql',primary_key_columns='AccountNumber',partition_column='',cluster_column='AccountNumber',cluster_buckets='8',optimize_where= '',optimize_z_order_by='',vacuum_retention_hours='168',load_type='MergeType2',delete_not_in_source='true',destination='goldgeneral',gold_zone_notebook_path='../Data Engineering/Gold Zone/Gold Load');
    onb.hydrate_gold_zone(project_name='UAT_SQL',system_name='UAT_SQL_adventureworkslt_enrich',system_secret_scope='internal',system_is_active=True,system_order=30,stage_name='UAT_SQL_adventureworkslt_enrich_daily',stage_is_active=True,stage_order=20,job_name='UAT_SQL_sales',job_is_active=True,job_order=10,view_name='silvergeneral.UAT_SQL_sales',table_name='goldgeneral.UAT_SQL_sales',purpose='uatsql',primary_key_columns='AccountNumber',partition_column='',cluster_column='AccountNumber',cluster_buckets='8',optimize_where= '',optimize_z_order_by='',vacuum_retention_hours='168',load_type='Overwrite',delete_not_in_source='true',destination='goldgeneral',gold_zone_notebook_path='../Data Engineering/Gold Zone/Gold Load');
    onb.update_stage_threads(project_name=project_name, stage_name="UAT_SQL_adventureworkslt_enrich_daily", threads=2)

    onb.hydrate_gold_zone(project_name='UAT_SQL',system_name='UAT_SQL_adventureworkslt_enrich',system_secret_scope='internal',system_is_active=True,system_order=30,stage_name='UAT_SQL_adventureworkslt_enrich_daily_rerun',stage_is_active=True,stage_order=30,job_name='UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader_rerun',job_is_active=True,job_order=10,view_name='silvergeneral.vadventureworkslt_saleslt_salesorderheader',table_name='goldgeneral.adventureworkslt_saleslt_salesorderheader',purpose='uatsql',primary_key_columns='AccountNumber',partition_column='',cluster_column='AccountNumber',cluster_buckets='8',optimize_where= '',optimize_z_order_by='',vacuum_retention_hours='168',load_type='MergeType2',delete_not_in_source='true',destination='goldgeneral',gold_zone_notebook_path='../Data Engineering/Gold Zone/Gold Load');
    onb.hydrate_gold_zone(project_name='UAT_SQL',system_name='UAT_SQL_adventureworkslt_enrich',system_secret_scope='internal',system_is_active=True,system_order=30,stage_name='UAT_SQL_adventureworkslt_enrich_daily_rerun',stage_is_active=True,stage_order=30,job_name='UAT_SQL_sales_rerun',job_is_active=True,job_order=10,view_name='silvergeneral.UAT_SQL_sales',table_name='goldgeneral.UAT_SQL_sales',purpose='uatsql',primary_key_columns='AccountNumber',partition_column='',cluster_column='AccountNumber',cluster_buckets='8',optimize_where= '',optimize_z_order_by='',vacuum_retention_hours='168',load_type='Overwrite',delete_not_in_source='true',destination='goldgeneral',gold_zone_notebook_path='../Data Engineering/Gold Zone/Gold Load');
    onb.update_stage_threads(project_name=project_name, stage_name='UAT_SQL_adventureworkslt_enrich_daily_rerun', threads=2)    

    #hydrate presentation zone
    onb.hydrate_presentation_zone(project_name='UAT_SQL',system_name='UAT_SQL_Load',system_secret_scope='internal',system_is_active=True,system_order=40,stage_name='UAT_SQL_Load_DW_Daily',stage_is_active=True,stage_order=10,job_name='UAT_SQL_adventureworkslt_SalesLT_ProductModel_upsert',job_is_active=True,job_order=10,table_name='goldgeneral.UAT_SQL_sales',destination_schema_name='dbo', stored_procedure_name='',save_mode='overwrite',presentation_zone_notebook_path='../Data Engineering/Presentation Zone/SQL JDBC')
    onb.hydrate_platinum_zone(project_name='UAT_SQL',system_name='UAT_SQL_Load',system_secret_scope='internal',system_is_active=True,system_order=40,stage_name='UAT_SQL_Load_DW_Daily',stage_is_active=True,stage_order=10,job_name='UAT_SQL_adventureworkslt_saleslt_salesorderheader_upsert',job_is_active=True,job_order=10,table_name='goldgeneral.adventureworkslt_saleslt_salesorderheader',destination_schema_name='dbo',destination_table_name='UAT_SQL_adventureworkslt_saleslt_salesorderheader',stored_procedure_name='',num_partitions='8',ignore_date_to_process_filter='true',load_type='overwrite',truncate_table_instead_of_drop_and_replace='true',isolation_level='READ_COMMITTED',presentation_zone_notebook_path='../Data Engineering/Presentation Zone/SQL Spark Connector 3')
    onb.update_stage_threads(project_name=project_name, stage_name='UAT_SQL_Load_DW_Daily, threads=2')

    #hydrate data quality assessment
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_Bronze_Zone_QC',stage_is_active=True,stage_order=10,job_name='UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_saleslt_address_staging',job_is_active=True,job_order=10,table_name='bronze.adventureworkslt_saleslt_address_staging',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_Bronze_Zone_QC',stage_is_active=True,stage_order=10,job_name='UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_saleslt_address_staging',job_is_active=True,job_order=10,table_name='bronze.adventureworkslt_saleslt_productmodel_staging',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_Bronze_Zone_QC',stage_is_active=True,stage_order=10,job_name='UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_saleslt_address_staging',job_is_active=True,job_order=10,table_name='bronze.adventureworkslt_saleslt_salesorderheader_staging',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_Bronze_Zone_QC',stage_is_active=True,stage_order=10,job_name='UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_saleslt_address_staging',job_is_active=True,job_order=10,table_name='bronze.adventureworkslt_dbo_buildversion_staging',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.update_stage_threads(project_name=project_name, stage_name="UAT_Bronze_Zone_QC", threads=4)

    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_SQL_Silver_Zone_QC',stage_is_active=True,stage_order=20,job_name='UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_saleslt_salesorderheader',job_is_active=True,job_order=10,table_name='silvergeneral.adventureworkslt_saleslt_salesorderheader',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_SQL_Silver_Zone_QC',stage_is_active=True,stage_order=20,job_name='UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_saleslt_salesorderheader',job_is_active=True,job_order=10,table_name='silvergeneral.adventureworkslt_saleslt_productmodel',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_SQL_Silver_Zone_QC',stage_is_active=True,stage_order=20,job_name='UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_saleslt_salesorderheader',job_is_active=True,job_order=10,table_name='silvergeneral.adventureworkslt_dbo_buildversion',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_SQL_Silver_Zone_QC',stage_is_active=True,stage_order=20,job_name='UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_saleslt_salesorderheader',job_is_active=True,job_order=10,table_name='silverprotected.adventureworkslt_saleslt_address',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.update_stage_threads(project_name=project_name, stage_name="UAT_SQL_Silver_Zone_QC", threads=4)

    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_SQL_Gold_Zone_QC',stage_is_active=True,stage_order=30,job_name='UAT_SQL_Gold_Zone_QC_dataqualityassessment_goldgeneral_adventureworkslt_saleslt_salesorderheader',job_is_active=True,job_order=10,table_name='goldgeneral.adventureworkslt_saleslt_salesorderheader',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.hydrate_data_quality_assessment(project_name='UAT_SQL',system_name='UAT_SQL_DataQuality',system_secret_scope='internal',system_is_active=True, system_order=50,stage_name='UAT_SQL_Gold_Zone_QC',stage_is_active=True,stage_order=30,job_name='UAT_SQL_Gold_Zone_QC_dataqualityassessment_goldgeneral_adventureworkslt_saleslt_salesorderheader',job_is_active=True,job_order=10,table_name='goldgeneral.UAT_SQL_sales',delta_history_minutes=-1,notebook_path='../Data Quality Rules Engine/Data Quality Assessment')
    onb.update_stage_threads(project_name=project_name, stage_name='UAT_SQL_Gold_Zone_QC', threads=2)    

    onb.load_orchestration_tables(project_name="UAT_SQL")
