CREATE TABLE [dbo].[Users_AppInsights]
(
	 [SK] BIGINT NOT NULL IDENTITY(1,1)
	,[Tool] VARCHAR(20) NOT NULL
	,[ContextSessionId] VARCHAR(20) NOT NULL
	,[Date] DATE NOT NULL
	,[UserID] UNIQUEIDENTIFIER NOT NULL
	,[RoleID] UNIQUEIDENTIFIER NOT NULL
	,[SegmentID] UNIQUEIDENTIFIER NOT NULL
	,[City] VARCHAR(100) NOT NULL
	,[Country] VARCHAR(100) NOT NULL
	,[Province] VARCHAR(100) NOT NULL
)
GO
ALTER TABLE dbo.Users_AppInsights ADD CONSTRAINT PK_CIX_dbo_Users_AppInsights PRIMARY KEY CLUSTERED([SK]);
GO
CREATE NONCLUSTERED INDEX IX_dbo_Users_AppInsights_Date ON dbo.Users_AppInsights ([Date]);

