/************************************************************************************/
-- Batch Pipeline Hydration
/************************************************************************************/
GO

EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Backfill'  ,@StageIsActive = 0  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_Customer'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'Customer'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '847'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 1  ,@WindowingColumn = 'ModifiedDate', @WindowedExtractionBeginDate = '2005-01-01'  ,@WindowedExtractionEndDate = '2010-01-01'  ,@WindowedExtractionInterval = 'Y'  ,@WindowedExtractionProcessLatestWindowFirst = 1  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'CustomerID', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Backfill'  ,@StageIsActive = 0  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_ProductModel'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'ProductModel'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '128'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 1  , @WindowingColumn = 'ModifiedDate', @WindowedExtractionBeginDate = '2002-01-01'  ,@WindowedExtractionEndDate = '2021-01-01'  ,@WindowedExtractionInterval = 'Y'  ,@WindowedExtractionProcessLatestWindowFirst = 0  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductModelID', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
GO
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_SalesOrderHeader'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'SalesOrderHeader'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '32'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'SalesOrderID',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'DueDate,ModifiedDate,OrderDate,ShipDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_dbo_BuildVersion'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'dbo'  ,@TableName = 'BuildVersion'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '1'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'SystemInformationID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_dbo_ErrorLog'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'dbo'  ,@TableName = 'ErrorLog'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '0'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = 'SELECT * FROM dbo.ErrorLog WHERE ErrorTime >= DATEADD(DAY, -30, SYSDATETIME())'  ,@PrimaryKeyColumns = 'ErrorLogID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_ProductModelProductDescription'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'ProductModelProductDescription'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '762'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductModelID, ProductDescriptionID, Culture', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_ProductCategory'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'ProductCategory'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '41'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductCategoryID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_CustomerAddress'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'CustomerAddress'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '417'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'CustomerID, AddressID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_ProductModel'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'ProductModel'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '128'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 1  , @WindowingColumn = 'ModifiedDate', @WindowedExtractionBeginDate = '2002-01-01'  ,@WindowedExtractionEndDate = '2021-01-01'  ,@WindowedExtractionInterval = 'Y'  ,@WindowedExtractionProcessLatestWindowFirst = 0  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductModelID',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'ModifiedDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_SalesOrderDetail'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'SalesOrderDetail'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '542'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'SalesOrderID, SalesOrderDetailID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_Product'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'Product'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '295'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_Customer'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'Customer'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '847'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 1  ,@WindowingColumn = 'ModifiedDate', @WindowedExtractionBeginDate = '2005-01-01'  ,@WindowedExtractionEndDate = '2010-01-01'  ,@WindowedExtractionInterval = 'Y'  ,@WindowedExtractionProcessLatestWindowFirst = 1  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'CustomerID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_Address'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'Address'  ,@SilverZonePartitionColumn = 'StateProvince'  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '450'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'AddressID', @ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'ModifiedDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = 'AddressLine1,AddressLine2', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'adventureworkslt'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'adventureworkslt_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_ProductDescription'  ,@JobIsActive = 0  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'ProductDescription'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '762'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductDescriptionID', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
GO
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'Batch Pipeline', @SystemName = 'externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'externalfilesystem_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'dvcpmdpcvsa_dvcatalystexternaldata_csv_noaa_noaaapi', @JobIsActive = 1, @JobOrder = 10, @ExternalDataPath = 'csv/noaa', @SchemaName = 'noaa', @TableName = 'noaaapi', @FileExtension = '', @Delimiter = ',', @Header = 'True', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'Date,ABC,DEF',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'Date',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File CSV', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'Batch Pipeline', @SystemName = 'externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'externalfilesystem_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'dvcpmdpcvsa_dvcatalystexternaldata_json_youtube_youtube', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'json/youtube', @SchemaName = 'youtube', @TableName = 'youtube', @FileExtension = 'json', @MultiLine = 'True', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = 'items_id_kind', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = 'items_id_kind', @NumPartitions = '8', @PrimaryKeyColumns = 'items_etag',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File JSON', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'Batch Pipeline', @SystemName = 'externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'externalfilesystem_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'dvcpmdpcvsa_dvcatalystexternaldata_parquet_userdata_userdata1', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'parquet/userdata', @SchemaName = 'userdata', @TableName = 'userdata1', @FileExtension = 'parquet', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'id',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'registration_dttm',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = 'cc,birthdate,email,first_name,ip_address,last_name,salary', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File Parquet', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
GO
EXEC [dbo].[HydrateCosmos] @ProjectName = 'Batch Pipeline', @SystemName = 'cosmosdbingest', @SystemSecretScope = 'CosmosDB', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'cosmosdbingest_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'cosmosdbingest_dvcatalyst_usecases', @JobIsActive = 1, @JobOrder = 10, @Collection = 'usecases', @PartitionColumn = '/usecaseId', @SchemaName = 'cosmosdbingest', @TableName = 'usecases', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NumPartitions = '8', @PrimaryKeyColumns = 'messages_message_messageId,anonymizedMethods_method,name',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silverprotected', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch CosmosDB', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
GO
EXEC [dbo].[HydrateGoldZonePowerBI]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'Export CSV Files'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40  ,@StageName = 'ExportCSVFiles_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_saleslt_salesorderheader'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@TableName = 'silvergeneral.adventureworkslt_saleslt_salesorderheader'  ,@CleansePath = 1  ,@RenameFile = 1  ,@GoldZoneNotebookPath = '../Data Engineering/Gold Zone/Power BI File';
GO
EXEC [dbo].[HydratePresentationZone]    @ProjectName = 'Batch Pipeline'  ,@SystemName = 'Load DW'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50  ,@StageName = 'LoadDW_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_SalesLT_ProductModel_upsert'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@TableName = 'adventureworkslt_SalesLT_ProductModel_upsert'  ,@DestinationSchemaName = 'dbo'  ,@StoredProcedureName = ''  ,@SaveMode = 'overwrite'  , @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL JDBC';
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'Batch Pipeline' ,@SystemName = 'Load DW'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'LoadDW_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'adventureworkslt_saleslt_salesorderheader'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@TableName = 'silvergeneral.adventureworkslt_saleslt_salesorderheader'  ,@DestinationSchemaName = 'dbo', @DestinationTableName='BatchPipeline_adventureworkslt_saleslt_salesorderheader'  ,@StoredProcedureName = ''  ,@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='true', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
EXEC [dbo].[HydratePresentationZone]    @ProjectName = 'Batch Pipeline'  ,@SystemName = "Load Cosmos", @SystemSecretScope = 'CosmosDB', @SystemIsActive = 1, @SystemOrder = 60, @StageName = 'LoadCosmos_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'adventureworkslt_SalesLT_Address_cdb', @JobIsActive = 1, @JobOrder = 10, @CollectionName = 'addresses', @TableName = 'adventureworkslt_SalesLT_Address', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/Cosmos DB';
GO
--Set desired parallelism for Jobs
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('adventureworkslt_Daily');
UPDATE dbo.Stage SET NumberOfThreads = 1 WHERE StageName IN ('cosmosdbingest','ExportCSVFiles_Daily');
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName IN ('LoadDW_Daily','adventureworkslt_Backfill');
UPDATE dbo.Stage SET NumberOfThreads = 3 WHERE StageName IN ('externalfilesystem_Daily');
GO
/************************************************************************************/
-- Streaming Pipeline Hydration
/************************************************************************************/
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'dataSource' AS ParameterName, 'test' AS ParameterValue
UNION
SELECT 'hashtag', 'Databricks'
UNION
SELECT 'eventHubExternalSystem', 'EventHubTwitterIngestion'
UNION
SELECT 'twitterExternalSystem', 'TwitterAPI'
UNION
SELECT 'timeoutSeconds', '60';
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'Streaming Pipeline'  ,@SystemName = 'Twitter'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 10  ,@StageName = 'Twitter_API'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'twitter_databricks_hashtag_to_eventhub'  ,@JobIsActive = 1  ,@JobOrder = 10, @Parameters=@Parameters ,@NotebookPath = '../Development/Send Tweets To Event Hub';
GO
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'Streaming Pipeline', @SystemName = 'Twitter', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'Twitter_EH_Ingest', @StageIsActive = 1, @StageOrder = 20, @JobName = 'twitter_databricks_eventhub_to_datalake', @JobIsActive = 1, @JobOrder = 10, @ExternalSystem = 'EventHubTwitterIngestion', @Trigger = 'Once', @MaxEventsPerTrigger = 10000, @Offset = 0, @Interval = 60, @TableName = 'databrickstweets', @Destination = 'silvergeneral', @NotebookPath = '../Data Engineering/Streaming/Ingest Event Hub';
GO
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'Streaming Pipeline', @SystemName = 'Twitter', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'Twitter_Sentiment', @StageIsActive = 1, @StageOrder = 30, @JobName = 'twitter_databricks_sentiment_analysis', @JobIsActive = 1, @JobOrder = 10, @ExternalSystem = 'CognitiveServices', @Trigger = 'Once', @MaxEventsPerTrigger = 10000, @Interval = 60, @TableName = 'databrickstweets', @Destination = 'silvergeneral', @ColumnName = 'Body', @OutputTableName = 'databrickstweetsscored', @NotebookPath = '../Data Engineering/Streaming/Sentiment Analysis using Azure Cognitive Services';
GO
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'Streaming Pipeline', @SystemName = 'Twitter', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'Twitter_EH_Output', @StageIsActive = 1, @StageOrder = 40, @JobName = 'twitter_datalake_to_eventhub', @JobIsActive = 1, @JobOrder = 10, @ExternalSystem = 'EventHubTwitterDistribution', @Trigger = 'Once', @MaxEventsPerTrigger = 10000, @Interval = 60, @TableName = 'databrickstweetsscored', @NotebookPath = '../Data Engineering/Streaming/Output to Event Hub';
GO
UPDATE dbo.Stage SET NumberOfThreads = 1 WHERE StageName IN('Twitter_API', 'Twitter_EH_Ingest', 'Twitter_Sentiment', 'Twitter_EH_Output');
GO
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'eventHubExternalSystem' AS ParameterName, 'EventHubCVIngestion' AS ParameterValue
UNION
SELECT 'messageCount', '10'
UNION
SELECT 'sleepSecondsBetweenMessages', '.5';
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'Streaming Pipeline'  ,@SystemName = 'ConnectedVehicle'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'CV'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'cv_to_eventhub'  ,@JobIsActive = 1  ,@JobOrder = 10, @Parameters=@Parameters ,@NotebookPath = '../Development/Send JSON Payload to Event Hub';
GO
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'Streaming Pipeline', @SystemName = 'ConnectedVehicle', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'CV', @StageIsActive = 1, @StageOrder = 10, @JobName = 'cv_ingest_eventhub', @JobIsActive = 1, @JobOrder = 20, @ExternalSystem = 'EventHubCVIngestion', @Trigger = 'Microbatch', @MaxEventsPerTrigger = 10000, @Offset = -1, @Interval = 10, @StopSeconds = 120, @TableName = 'cvpayload', @Destination = 'silvergeneral', @NotebookPath = '../Data Engineering/Streaming/Ingest Event Hub';
GO
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'Streaming Pipeline', @SystemName = 'ConnectedVehicle', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'CV', @StageIsActive = 1, @StageOrder = 10, @JobName = 'cv_flatten', @JobIsActive = 1, @JobOrder = 30, @ExternalSystem = 'internal', @Trigger = 'Microbatch', @MaxEventsPerTrigger = 10000, @Offset = 0, @Interval = 10, @StopSeconds = 120, @TableName = 'cvpayload', @Destination = 'silvergeneral', @ColumnName = 'Body', @OutputTableName = 'cvflattened', @NotebookPath = '../Data Engineering/Streaming/Flatten JSON';
GO
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'Streaming Pipeline', @SystemName = 'ConnectedVehicle', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'CV', @StageIsActive = 1, @StageOrder = 10, @JobName = 'cv_distribution_eventhub', @JobIsActive = 1, @JobOrder = 40, @ExternalSystem = 'EventHubCVDistribution', @Trigger = 'Microbatch', @Interval = 10, @StopSeconds = 120, @TableName = 'cvflattened', @NotebookPath = '../Data Engineering/Streaming/Output to Event Hub';
GO
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName = 'CV';
GO
/************************************************************************************/
-- ADX Pipeline Hydration
/************************************************************************************/
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'ADX Pipeline', @SystemName = 'ConnectedVehicle_adx', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'CV_adx', @StageIsActive = 1, @StageOrder = 10, @JobName = 'cvflattened_adx', @JobIsActive = 1, @JobOrder = 10, @ExternalSystem = 'AzureDataExplorer', @Trigger = 'Microbatch', @Interval = 10, @StopSeconds = 120, @DatabaseName = 'connectedvehicle', @TableName = 'cvflattened', @OutputTableName = 'cvflattened', @NotebookPath = '../Data Engineering/Streaming/Output to Azure Data Explorer';
EXEC [dbo].[HydratePresentationZone] @ProjectName = 'ADX Pipeline', @SystemName = 'ConnectedVehicle_adx', @SystemSecretScope = 'AzureDataExplorer', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'CV_adx', @StageIsActive = 1, @StageOrder = 10, @JobName = 'noaa_noaaapi_adx', @JobIsActive = 1, @JobOrder = 20, @DatabaseName = 'connectedvehicle', @TableName = 'noaa_noaaapi', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/Azure Data Explorer';
GO
/************************************************************************************/
-- Table Maintenance Pipeline Hydration
/************************************************************************************/
EXEC [dbo].[HydrateSparkTableMaintenance] @ProjectName = 'Table Maintenance', @SystemName = 'ConnectedVehicle_maint', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'SparkTableMaintenance', @StageIsActive = 1, @StageOrder = 10, @JobName = 'maint_cvpayload', @JobIsActive = 1, @JobOrder = 10, @TableName = 'cvpayload', @RunOptimize = '1', @RunVacuum = '1', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NotebookPath = '../Orchestration/Spark Table Maintenance';
EXEC [dbo].[HydrateSparkTableMaintenance] @ProjectName = 'Table Maintenance', @SystemName = 'ConnectedVehicle_maint', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'SparkTableMaintenance', @StageIsActive = 1, @StageOrder = 10, @JobName = 'maint_cvflattened', @JobIsActive = 1, @JobOrder = 10, @TableName = 'cvflattened', @RunOptimize = '1', @RunVacuum = '1', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NotebookPath = '../Orchestration/Spark Table Maintenance';
EXEC [dbo].[HydrateSparkTableMaintenance] @ProjectName = 'Table Maintenance', @SystemName = 'ConnectedVehicle_maint', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'SparkTableMaintenance', @StageIsActive = 1, @StageOrder = 10, @JobName = 'maint_databrickstweets', @JobIsActive = 1, @JobOrder = 10, @TableName = 'databrickstweets', @RunOptimize = '1', @RunVacuum = '1', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NotebookPath = '../Orchestration/Spark Table Maintenance';
EXEC [dbo].[HydrateSparkTableMaintenance] @ProjectName = 'Table Maintenance', @SystemName = 'ConnectedVehicle_maint', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'SparkTableMaintenance', @StageIsActive = 1, @StageOrder = 10, @JobName = 'maint_databrickstweetsscored', @JobIsActive = 1, @JobOrder = 10, @TableName = 'databrickstweetsscored', @RunOptimize = '1', @RunVacuum = '1', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NotebookPath = '../Orchestration/Spark Table Maintenance';
GO
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName = 'SparkTableMaintenance';
GO
/************************************************************************************/
-- ML Pipeline Hydration
/************************************************************************************/
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'tableName' AS ParameterName, 'bikesharingml' AS ParameterValue
UNION
SELECT 'deltaHistoryMinutes', '-1'
UNION
SELECT 'samplePercent', '.5';
EXEC [dbo].[HydrateGenericNotebook] @ProjectName = 'ML Pipeline',@SystemName = 'mlpipeline',@SystemSecretScope = 'internal',@SystemIsActive = 1,@SystemOrder = 10,@StageName = 'bikesharingml',@StageIsActive = 1,@StageOrder = 10,@JobName = 'bikesharingml_data_profiling',@JobIsActive = 1,@JobOrder = 10, @Parameters=@Parameters,@NotebookPath = '../Exploratory Data Analysis/Data Profiling';
GO
EXEC [dbo].[HydrateMLExperimentTraining] @ProjectName = 'ML Pipeline',@SystemName = 'mlpipeline',@SystemSecretScope = 'internal',@SystemOrder = 10,@SystemIsActive = 1,@StageName = 'bikesharingml',@StageIsActive = 1,@StageOrder = 10,@JobName = 'bikesharingml_train_linear_regression',@JobOrder = 20,@JobIsActive = 1,@TableName = 'bikesharingml',@ExperimentName = 'Bike Sharing Linear Regression',@ExperimentId = '',@ExcludedColumns = 'instant,dteday,temp,casual,registered',@Label = 'cnt',@ContinuousColumns = '',@RegularizationParameters = '0.1, 0.01',@PredictionColumn = 'prediction',@Folds = '2',@TrainTestSplit = '0.7, 0.3',@NotebookPath = '../ML/spark/Train Linear Regression';
EXEC [dbo].[HydrateMLBatchInference] @ProjectName = 'ML Pipeline',@SystemName = 'mlpipeline',@SystemSecretScope = 'internal',@SystemOrder = 10,@SystemIsActive = 1,@StageName = 'bikesharingml',@StageIsActive = 1,@StageOrder = 10,@JobName = 'bikesharingml_batch_inference',@JobOrder = 30,@JobIsActive = 1,@ExperimentNotebookPath = '../ML/spark/Train Linear Regression',@ExperimentId = '',@MetricClause = 'metrics.avg_rmse DESC',@TableName = 'bikesharingml',@DeltaHistoryMinutes = -1,@ExcludedColumns = 'instant,dteday,temp,casual,registered',@Partitions = '8',@PrimaryKeyColumns = '',@DestinationTableName = 'bikesharingpredictions',@PartitionCol = '',@ClusterCol = 'pk',@ClusterBuckets = '50',@OptimizeWhere = '',@OptimizeZOrderBy = '',@VacuumRetentionHours = 168,@LoadType = 'Overwrite',@Destination = 'silvergeneral',@NotebookPath = '../ML/Batch Inference'
EXEC [dbo].[HydrateMLStreamingInference] @ProjectName = 'ML Pipeline',@SystemName = 'mlpipeline',@SystemSecretScope = 'internal',@SystemOrder = 10,@SystemIsActive = 1,@StageName = 'bikesharingml',@StageIsActive = 1,@StageOrder = 10,@JobName = 'bikesharingml_streaming_inference',@JobOrder = 40,@JobIsActive = 1,@ExperimentNotebookPath = '../ML/spark/Train Linear Regression',@ExperimentId = '',@MetricClause = 'metrics.avg_rmse DESC',@TableName = 'bikesharingml',@ExcludedColumns = 'instant,dteday,temp,casual,registered',@DestinationTableName = 'bikesharingpredictionsstreaming',@Destination = 'silvergeneral',@NotebookPath = '../ML/Streaming Inference';
UPDATE dbo.Stage SET NumberOfThreads = 1 WHERE StageName = 'bikesharingml';
GO
