/************************************************************************************/
-- UAT_ADF Hydration
/************************************************************************************/
--FILES
EXEC [dbo].[HydrateADFBatchFile] @ProjectName = 'UAT_ADF',@SystemName = 'UAT_ADF_Files',@SystemOrder = 10,@SystemIsActive = 0,@StageName = 'UAT_ADF_Files_JSON',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ADF_Files_JSON',@JobOrder = 10,@JobIsActive = 1,@LocalFilePath = 'json',@LocalFileName = '*.json',@LocalEncoding = 'UTF-8',@Recursive = '1',@EnablePartitionDiscovery = '0',@DestinationContainerName = 'azuredatafactory',@DestinationFilePath = 'json',@DestinationEncoding = 'UTF-8',@ADFPipelineName = 'On Premises JSON to Staging';
EXEC [dbo].[HydrateADFBatchFile] @ProjectName = 'UAT_ADF',@SystemName = 'UAT_ADF_Files',@SystemOrder = 10,@SystemIsActive = 0,@StageName = 'UAT_ADF_Files_CSV',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ADF_Files_CSV',@JobOrder = 10,@JobIsActive = 1,@LocalFilePath = 'csv',@LocalFileName = '*.csv',@LocalEncoding = 'UTF-8',@Recursive = '1',@EnablePartitionDiscovery = '0',@DestinationContainerName = 'azuredatafactory',@DestinationFilePath = 'csv',@DestinationEncoding = 'UTF-8',@ADFPipelineName = 'On Premises Delimited to Staging',@RowDelimiter = '\r\n',@EscapeCharacter = '\\',@QuoteCharacter = '"',@FirstRowAsHeader = '1',@NullValue = 'NULL';
EXEC [dbo].[HydrateADFBatchFile] @ProjectName = 'UAT_ADF',@SystemName = 'UAT_ADF_Files',@SystemOrder = 10,@SystemIsActive = 0,@StageName = 'UAT_ADF_Files_Parquet',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ADF_Files_Parquet',@JobOrder = 10,@JobIsActive = 1,@LocalFilePath = 'parquet',@LocalFileName = '*.parquet',@Recursive = '1',@EnablePartitionDiscovery = '0',@DestinationContainerName = 'azuredatafactory',@DestinationFilePath = 'parquet',@ADFPipelineName = 'On Premises Parquet to Staging';
EXEC [dbo].[HydrateADFBatchFile] @ProjectName = 'UAT_ADF',@SystemName = 'UAT_ADF_Files',@SystemOrder = 10,@SystemIsActive = 0,@StageName = 'UAT_ADF_Files_XML',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ADF_Files_XML',@JobOrder = 10,@JobIsActive = 1,@LocalFilePath = 'xml',@LocalFileName = '*.xml',@Recursive = '1',@EnablePartitionDiscovery = '0',@DestinationContainerName = 'azuredatafactory',@DestinationFilePath = 'xml',@ADFPipelineName = 'On Premises XML to Staging', @Namespaces = '1', @DetectDataType = '1', @NullValue = 'NULL';
--TABLES
EXEC [dbo].[HydrateADFSQL]   @ProjectName = 'UAT_ADF'  ,@SystemName = 'UAT_ADF_SQL'  ,@SystemOrder = 10  ,@SystemIsActive = 1  ,@StageName = 'UAT_ADF_SQL_Daily_Tables'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'UAT_ADF_SQL_Daily_table_dbo_BuildVersion'  ,@JobOrder = 10  ,@JobIsActive = 1  ,@ServerName = 'ktkvdc.database.windows.net'  ,@DatabaseName = 'ktkvdc'  ,@UserName = 'armdeploymentadmin'  ,@PasswordKeyVaultSecretName = 'ExternalDatabasePwd'  ,@SchemaName = 'dbo'  ,@TableName = 'BuildVersion'  ,@DestinationContainerName = 'azuredatafactory'  ,@DestinationFilePath = 'adfsqlcollect/table/dbo/BuildVersion'  ,@ADFPipelineName = 'On Premises Database Table to Staging';
--SAMPLES/QUERIES
EXEC [dbo].[HydrateADFSQL]   @ProjectName = 'UAT_ADF'  ,@SystemName = 'UAT_ADF_SQL'  ,@SystemOrder = 10  ,@SystemIsActive = 1  ,@StageName = 'UAT_ADF_SQL_Daily_Queries'  ,@StageIsActive = 1  ,@StageOrder = 20  ,@JobName = 'UAT_ADF_SQL_Daily_query_SalesLT_Address'  ,@JobOrder = 10  ,@JobIsActive = 1  ,@ServerName = 'ktkvdc.database.windows.net'  ,@DatabaseName = 'ktkvdc'  ,@UserName = 'armdeploymentadmin'  ,@PasswordKeyVaultSecretName = 'ExternalDatabasePwd'  ,@SchemaName = 'SalesLT'  ,@TableName = 'Address'  ,@PushdownQuery = 'SELECT TOP 1000 * FROM [SalesLT].[Address]'  ,@DestinationContainerName = 'azuredatafactory'  ,@DestinationFilePath = 'adfsqlcollect/query/SalesLT/Address'  ,@ADFPipelineName = 'On Premises Database Query to Staging';
GO
/************************************************************************************/
-- UAT_SQL Hydration
/************************************************************************************/
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'bogus' AS ParameterName, 'bogus' AS ParameterValue --at least 1 parameter is required, this is meaningless
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'UAT_SQL', @SystemName = 'UAT_SQL_Teardown', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_SQL_Teardown_daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_SQL_Teardown', @JobIsActive = 1, @JobOrder = 10, @Parameters=@Parameters, @NotebookPath = '../Data Quality Rules Engine/UAT_SQL_Teardown';
GO 
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'SalesOrderHeader'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '32'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'SalesOrderID',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'DueDate,ModifiedDate,OrderDate,ShipDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'UAT_SQL_adventureworkslt_dbo_BuildVersion'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'dbo'  ,@TableName = 'BuildVersion'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '0'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = 'SELECT * FROM dbo.BuildVersion WHERE 1=1 OR ModifiedDate >= DATEADD(DAY, -30, SYSDATETIME())'  ,@PrimaryKeyColumns = 'SystemInformationID', @LoadType = 'Append', @Destination = 'silvergeneral'  ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'UAT_SQL_adventureworkslt_SalesLT_ProductModel'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'ProductModel'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '128'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 1  , @WindowingColumn = 'ModifiedDate', @WindowedExtractionBeginDate = '2002-01-01'  ,@WindowedExtractionEndDate = '2021-01-01'  ,@WindowedExtractionInterval = 'Y'  ,@WindowedExtractionProcessLatestWindowFirst = 0  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductModelID',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'ModifiedDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral'  ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'UAT_SQL_adventureworkslt_SalesLT_Address'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'Address'  ,@SilverZonePartitionColumn = 'StateProvince'  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '450'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'AddressID', @ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'ModifiedDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = 'AddressLine1,AddressLine2', @LoadType = 'Overwrite', @Destination = 'silverprotected'  ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_SQL_adventureworkslt_ingest_daily');
GO --rerun the stage a second time to check for issues with merge etc.
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily_rerun'  ,@StageIsActive = 1  ,@StageOrder = 20  ,@JobName = 'UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader_rerun'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'SalesOrderHeader'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '32'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'SalesOrderID',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'DueDate,ModifiedDate,OrderDate,ShipDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral'    ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily_rerun'  ,@StageIsActive = 1  ,@StageOrder = 20  ,@JobName = 'UAT_SQL_adventureworkslt_dbo_BuildVersion_rerun'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'dbo'  ,@TableName = 'BuildVersion'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '0'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = 'SELECT * FROM dbo.BuildVersion WHERE 1=1 OR ModifiedDate >= DATEADD(DAY, -30, SYSDATETIME())'  ,@PrimaryKeyColumns = 'SystemInformationID', @LoadType = 'Append', @Destination = 'silvergeneral'  ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily_rerun'  ,@StageIsActive = 1  ,@StageOrder = 20  ,@JobName = 'UAT_SQL_adventureworkslt_SalesLT_ProductModel_rerun'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'ProductModel'  ,@SilverZonePartitionColumn = ''  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '128'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 1  , @WindowingColumn = 'ModifiedDate', @WindowedExtractionBeginDate = '2002-01-01'  ,@WindowedExtractionEndDate = '2021-01-01'  ,@WindowedExtractionInterval = 'Y'  ,@WindowedExtractionProcessLatestWindowFirst = 0  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'ProductModelID',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'ModifiedDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral'  ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchSQL]    @ProjectName = 'UAT_SQL'  ,@SystemName = 'UAT_SQL_adventureworkslt_ingest'  ,@SystemSecretScope = 'adventureworkslt'  ,@SystemIsActive = 1  ,@SystemOrder = 20  ,@StageName = 'UAT_SQL_adventureworkslt_ingest_daily_rerun'  ,@StageIsActive = 1  ,@StageOrder = 20  ,@JobName = 'UAT_SQL_adventureworkslt_SalesLT_Address_rerun'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@SchemaName = 'SalesLT'  ,@TableName = 'Address'  ,@SilverZonePartitionColumn = 'StateProvince'  ,@SilverZoneClusterColumn = 'pk'  ,@SilverZoneClusterBuckets = '8'  ,@OptimizeWhere = ''  ,@OptimizeZOrderBy = ''  ,@VacuumRetentionHours = 168  ,@PartitionColumn = ''  ,@LowerBound = '0'  ,@UpperBound = '450'  ,@NumPartitions = '8'  ,@useWindowedExtraction = 0  ,@WindowedExtractionBeginDate = NULL  ,@WindowedExtractionEndDate = NULL  ,@WindowedExtractionInterval = NULL  ,@WindowedExtractionProcessLatestWindowFirst = NULL  ,@pushdownQuery = ''  ,@PrimaryKeyColumns = 'AddressID', @ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'ModifiedDate',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = 'AddressLine1,AddressLine2', @LoadType = 'Overwrite', @Destination = 'silverprotected'  ,@BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch SQL'  ,@SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_SQL_adventureworkslt_ingest_daily_rerun');
GO
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'bogus' AS ParameterName, 'bogus' AS ParameterValue --at least 1 parameter is required, this is meaningless
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'UAT_SQL', @SystemName = 'UAT_SQL_adventureworkslt_enrich', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_SQL_adventureworkslt_prep_daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_SQL_Gold_Load_Views', @JobIsActive = 1, @JobOrder = 10, @Parameters=@Parameters, @NotebookPath = '../Data Quality Rules Engine/UAT_SQL';
GO 
EXEC [dbo].[HydrateGoldZone] @ProjectName = 'UAT_SQL', @SystemName = 'UAT_SQL_adventureworkslt_enrich', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_SQL_adventureworkslt_enrich_daily', @StageIsActive = 1, @StageOrder = 20 , @JobName = 'UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader', @JobIsActive = 1, @JobOrder = 10, @ViewName = 'silvergeneral.vadventureworkslt_saleslt_salesorderheader', @TableName = 'goldgeneral.adventureworkslt_saleslt_salesorderheader', @Purpose = 'uatsql', @PrimaryKeyColumns = 'AccountNumber', @PartitionColumn = '', @ClusterColumn = 'AccountNumber', @ClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = '168', @LoadType = 'MergeType2', @DeleteNotInSource = 'true', @Destination = 'goldgeneral', @GoldZoneNotebookPath = '../Data Engineering/Gold Zone/Gold Load';
EXEC [dbo].[HydrateGoldZone] @ProjectName = 'UAT_SQL', @SystemName = 'UAT_SQL_adventureworkslt_enrich', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_SQL_adventureworkslt_enrich_daily', @StageIsActive = 1, @StageOrder = 20 , @JobName = 'UAT_SQL_sales', @JobIsActive = 1, @JobOrder = 10, @ViewName = 'silvergeneral.UAT_SQL_sales', @TableName = 'goldgeneral.UAT_SQL_sales', @Purpose = 'uatsql', @PrimaryKeyColumns = 'AccountNumber', @PartitionColumn = '', @ClusterColumn = 'AccountNumber', @ClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = '168', @LoadType = 'Overwrite', @DeleteNotInSource = 'true', @Destination = 'goldgeneral', @GoldZoneNotebookPath = '../Data Engineering/Gold Zone/Gold Load';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_SQL_adventureworkslt_enrich_daily';
GO --rerun the stage a second time to check for issues with merge etc.
EXEC [dbo].[HydrateGoldZone] @ProjectName = 'UAT_SQL', @SystemName = 'UAT_SQL_adventureworkslt_enrich', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_SQL_adventureworkslt_enrich_daily_rerun', @StageIsActive = 1, @StageOrder = 30 , @JobName = 'UAT_SQL_adventureworkslt_SalesLT_SalesOrderHeader_rerun', @JobIsActive = 1, @JobOrder = 10, @ViewName = 'silvergeneral.vadventureworkslt_saleslt_salesorderheader', @TableName = 'goldgeneral.adventureworkslt_saleslt_salesorderheader', @Purpose = 'uatsql', @PrimaryKeyColumns = 'AccountNumber', @PartitionColumn = '', @ClusterColumn = 'AccountNumber', @ClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = '168', @LoadType = 'MergeType2', @DeleteNotInSource = 'true', @Destination = 'goldgeneral', @GoldZoneNotebookPath = '../Data Engineering/Gold Zone/Gold Load';
EXEC [dbo].[HydrateGoldZone] @ProjectName = 'UAT_SQL', @SystemName = 'UAT_SQL_adventureworkslt_enrich', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_SQL_adventureworkslt_enrich_daily_rerun', @StageIsActive = 1, @StageOrder = 30 , @JobName = 'UAT_SQL_sales_rerun', @JobIsActive = 1, @JobOrder = 10, @ViewName = 'silvergeneral.UAT_SQL_sales', @TableName = 'goldgeneral.UAT_SQL_sales', @Purpose = 'uatsql', @PrimaryKeyColumns = 'AccountNumber', @PartitionColumn = '', @ClusterColumn = 'AccountNumber', @ClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = '168', @LoadType = 'Overwrite', @DeleteNotInSource = 'true', @Destination = 'goldgeneral', @GoldZoneNotebookPath = '../Data Engineering/Gold Zone/Gold Load';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_SQL_adventureworkslt_enrich_daily';
GO
EXEC [dbo].[HydratePresentationZone] @ProjectName = 'UAT_SQL' ,@SystemName = 'UAT_SQL_Load'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40  ,@StageName = 'UAT_SQL_Load_DW_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'UAT_SQL_adventureworkslt_SalesLT_ProductModel_upsert'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@TableName = 'goldgeneral.UAT_SQL_sales'  ,@DestinationSchemaName = 'dbo'  ,@StoredProcedureName = ''  ,@SaveMode = 'overwrite'  , @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL JDBC';
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_SQL' ,@SystemName = 'UAT_SQL_Load'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40  ,@StageName = 'UAT_SQL_Load_DW_Daily'  ,@StageIsActive = 1  ,@StageOrder = 10  ,@JobName = 'UAT_SQL_adventureworkslt_saleslt_salesorderheader_upsert'  ,@JobIsActive = 1  ,@JobOrder = 10  ,@TableName = 'goldgeneral.adventureworkslt_saleslt_salesorderheader'  ,@DestinationSchemaName = 'dbo', @DestinationTableName='UAT_SQL_adventureworkslt_saleslt_salesorderheader'  ,@StoredProcedureName = ''  ,@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='true', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName IN ('UAT_SQL_Load_DW_Daily');
GO
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10 ,@JobName = 'UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_saleslt_address_staging'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'bronze.adventureworkslt_saleslt_address_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10,@JobName = 'UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_saleslt_productmodel_staging'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'bronze.adventureworkslt_saleslt_productmodel_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10,@JobName = 'UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_saleslt_salesorderheader_staging'  ,@JobIsActive = 1  ,@JobOrder = 10 ,@TableName = 'bronze.adventureworkslt_saleslt_salesorderheader_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10,@JobName = 'UAT_SQL_Bronze_Zone_QC_dataqualityassessment_bronze_adventureworkslt_dbo_buildversion_staging'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'bronze.adventureworkslt_dbo_buildversion_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_SQL_Bronze_Zone_QC');
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_saleslt_salesorderheader'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.adventureworkslt_saleslt_salesorderheader'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_saleslt_productmodel'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.adventureworkslt_saleslt_productmodel'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_dbo_buildversion'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.adventureworkslt_dbo_buildversion'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_SQL_Silver_Zone_QC_dataqualityassessment_silver_adventureworkslt_saleslt_address'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silverprotected.adventureworkslt_saleslt_address'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_SQL_Silver_Zone_QC');
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Gold_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 30,@JobName = 'UAT_SQL_Gold_Zone_QC_dataqualityassessment_goldgeneral_adventureworkslt_saleslt_salesorderheader',@JobIsActive = 1,@JobOrder = 10,@TableName = 'goldgeneral.adventureworkslt_saleslt_salesorderheader',@DeltaHistoryMinutes = -1,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_SQL_Gold_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 30,@JobName = 'UAT_SQL_Gold_Zone_QC_dataqualityassessment_goldgeneral_UAT_SQL_sales',@JobIsActive = 1,@JobOrder = 10,@TableName = 'goldgeneral.UAT_SQL_sales',@DeltaHistoryMinutes = -1,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName IN ('UAT_SQL_Gold_Zone_QC');
GO
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 60,@StageName = 'UAT_SQL Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'dataqualityassessment_loadmetadatadb_dataqualityvalidationresult',@JobIsActive = 1,@JobOrder = 10,@TableName = 'goldprotected.dataqualityvalidationresult',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResult', @StoredProcedureName = 'staging.LoadDataQualityValidationResult',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_SQL',@SystemName = 'UAT_SQL_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 60,@StageName = 'UAT_SQL Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'dataqualityassessment_loadmetadatadb_dataqualityvalidationresultdetail',@JobIsActive = 1,@JobOrder = 20,@TableName = 'goldprotected.vdataqualityvalidationresultdetail',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResultDetail', @StoredProcedureName = 'staging.LoadDataQualityValidationResultDetail',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
UPDATE dbo.Stage SET NumberOfThreads = 1 WHERE StageName = 'UAT_SQL Data Quality Assessment Load to Metadata DB';
GO
/************************************************************************************/
-- UAT_ExternalFiles Hydration
/************************************************************************************/
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'bogus' AS ParameterName, 'bogus' AS ParameterValue --at least 1 parameter is required, this is meaningless
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_Teardown', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_ExternalFiles_Teardown_daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_ExternalFiles_Teardown', @JobIsActive = 1, @JobOrder = 10, @Parameters=@Parameters, @NotebookPath = '../Data Quality Rules Engine/UAT_ExternalFiles_Teardown';
GO 
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_csv_noaa_noaaapi', @JobIsActive = 1, @JobOrder = 10, @ExternalDataPath = 'csv/noaa', @SchemaName = 'noaa', @TableName = 'noaaapi', @FileExtension = '', @Delimiter = ',', @Header = 'True', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'Date,ABC,DEF',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'Date',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File CSV', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_json_youtube_youtube', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'json/youtube', @SchemaName = 'youtube', @TableName = 'youtube', @FileExtension = 'json', @MultiLine = 'True', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'items_etag',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File JSON', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_parquet_userdata_userdata1', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'parquet/userdata', @SchemaName = 'userdata', @TableName = 'userdata1', @FileExtension = 'parquet', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'id',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'registration_dttm',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = 'cc,birthdate,email,first_name,ip_address,last_name,salary', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File Parquet', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_xml_simple', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'xml/simple', @SchemaName = 'menu', @TableName = 'breakfast', @FileExtension = 'xml', @IsDatePartitioned = 'False', @RowTag = 'food', @RootTag = 'breakfast_menu', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = '',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Overwrite', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File XML', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_ExternalFiles_externalfilesystem_Daily');
GO
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily_rerun', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_csv_noaa_noaaapi_rerun', @JobIsActive = 1, @JobOrder = 10, @ExternalDataPath = 'csv/noaa', @SchemaName = 'noaa', @TableName = 'noaaapi', @FileExtension = '', @Delimiter = ',', @Header = 'True', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'Date,ABC,DEF',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'Date',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File CSV', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily_rerun', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_json_youtube_youtube_rerun', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'json/youtube', @SchemaName = 'youtube', @TableName = 'youtube', @FileExtension = 'json', @MultiLine = 'True', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'items_etag',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File JSON', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily_rerun', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_parquet_userdata_userdata1_rerun', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'parquet/userdata', @SchemaName = 'userdata', @TableName = 'userdata1', @FileExtension = 'parquet', @IsDatePartitioned = 'False', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = 'id',@ExplodeAndFlatten = 'False',@CleanseColumnNames = 'False',@TimestampColumns = 'registration_dttm',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = 'cc,birthdate,email,first_name,ip_address,last_name,salary', @LoadType = 'Merge', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File Parquet', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydrateBatchFile] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_ExternalFiles_externalfilesystem', @SystemSecretScope = 'ExternalBlobStore', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_ExternalFiles_externalfilesystem_Daily_rerun', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_ExternalFiles_dvcpmdpcvsa_dvcatalystexternaldata_xml_simple_rerun', @JobIsActive = 1, @JobOrder = 10,  @ExternalDataPath = 'xml/simple', @SchemaName = 'menu', @TableName = 'breakfast', @FileExtension = 'xml', @IsDatePartitioned = 'False', @RowTag = 'food', @RootTag = 'breakfast_menu', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @PartitionColumn = '', @NumPartitions = '8', @PrimaryKeyColumns = '',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Overwrite', @Destination = 'silvergeneral', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch File XML', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_ExternalFiles_externalfilesystem_Daily_rerun');
GO
EXEC [dbo].[HydrateGoldZonePowerBI] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_GoldZone', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_GoldZone', @StageIsActive = 1, @StageOrder = 10 , @JobName = 'UAT_GoldZone_externalblobstore_youtube_youtube', @JobIsActive = 1, @JobOrder = 10, @TableName = 'silvergeneral.externalblobstore_youtube_youtube', @CleansePath = 1, @RenameFile = 1, @GoldZoneNotebookPath = '../Data Engineering/Gold Zone/Power BI File';
EXEC [dbo].[HydrateClone] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_GoldZone', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_GoldZone', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_GoldZone_externalblobstore_userdata_userdata1', @JobIsActive = 1, @JobOrder = 10, @SourceTableName = 'silvergeneral.externalblobstore_userdata_userdata1', @Destination = 'sandbox', @DestinationRelativePath = 'uatgoldzone', @DestinationTableName = 'userdata_userdata1', @AppendTodaysDateToTableName = 'False', @OverwriteTable = 'True', @DestinationTableComment = 'uat gold zone testing clone', @CloneType = 'SHALLOW', @TimeTravelTimestampExpression = '', @TimeTravelVersionExpression = '', @LogRetentionDurationDAys = '7', @DeletedFileRetentionDurationDays = '7', @NotebookPath = '../Data Engineering/Sandbox Zone/Clone Table'
EXEC [dbo].[HydrateClone] @ProjectName = 'UAT_ExternalFiles_and_GoldZone', @SystemName = 'UAT_GoldZone', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 30, @StageName = 'UAT_GoldZone', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_GoldZone_externalblobstore_noaa_noaaapi', @JobIsActive = 1, @JobOrder = 10, @SourceTableName = 'silvergeneral.externalblobstore_noaa_noaaapi', @Destination = 'sandbox', @DestinationRelativePath = 'uatgoldzone', @DestinationTableName = 'noaa_noaaapi', @AppendTodaysDateToTableName = 'False', @OverwriteTable = 'True', @DestinationTableComment = 'uat gold zone testing clone', @CloneType = 'DEEP', @TimeTravelTimestampExpression = '', @TimeTravelVersionExpression = '', @LogRetentionDurationDAys = '7', @DeletedFileRetentionDurationDays = '7', @NotebookPath = '../Data Engineering/Sandbox Zone/Clone Table'
UPDATE dbo.Stage SET NumberOfThreads = 3 WHERE StageName IN ('UAT_GoldZone');
GO
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10 ,@JobName = 'UAT_ExternalFiles_Bronze_Zone_QC_dataqualityassessment_bronze_UAT_ExternalFiles'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'bronze.externalblobstore_noaa_noaaapi_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10,@JobName = 'UAT_ExternalFiles_Bronze_Zone_QC_dataqualityassessment_bronze_externalblobstore_userdata_userdata1_staging'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'bronze.externalblobstore_userdata_userdata1_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10,@JobName = 'UAT_ExternalFiles_Bronze_Zone_QC_dataqualityassessment_bronze_externalblobstore_youtube_youtube_staging'  ,@JobIsActive = 1  ,@JobOrder = 10 ,@TableName = 'bronze.externalblobstore_youtube_youtube_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Bronze_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10,@JobName = 'UAT_ExternalFiles_Bronze_Zone_QC_dataqualityassessment_bronze_externalblobstore_menu_breakfast_staging'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'bronze.externalblobstore_menu_breakfast_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_SQL_Bronze_Zone_QC');
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_ExternalFiles_Silver_Zone_QC_dataqualityassessment_silver_externalblobstore_noaa_noaaapi'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.externalblobstore_noaa_noaaapi'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_ExternalFiles_Silver_Zone_QC_dataqualityassessment_silver_externalblobstore_userdata_userdata1'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.externalblobstore_userdata_userdata1'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_ExternalFiles_Silver_Zone_QC_dataqualityassessment_silver_externalblobstore_youtube_youtube'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.externalblobstore_youtube_youtube'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 20,@JobName = 'UAT_ExternalFiles_Silver_Zone_QC_dataqualityassessment_silver_externalblobstore_menu_breakfast'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silverprotected.externalblobstore_menu_breakfast'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_SQL_Silver_Zone_QC');
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Gold_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 30,@JobName = 'UAT_ExternalFiles_Gold_Zone_QC_dataqualityassessment_sandbox_userdata_userdata1',@JobIsActive = 1,@JobOrder = 10,@TableName = 'sandbox.userdata_userdata1',@DeltaHistoryMinutes = -1,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment]    @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 40,@StageName = 'UAT_ExternalFiles_Gold_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 30,@JobName = 'UAT_ExternalFiles_Gold_Zone_QC_dataqualityassessment_sandbox_noaa_noaaapi',@JobIsActive = 1,@JobOrder = 10,@TableName = 'sandbox.noaa_noaaapi',@DeltaHistoryMinutes = -1,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName IN ('UAT_SQL_Gold_Zone_QC');
GO
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 60,@StageName = 'UAT_SQL Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'dataqualityassessment_loadmetadatadb_dataqualityvalidationresult',@JobIsActive = 1,@JobOrder = 10,@TableName = 'goldprotected.dataqualityvalidationresult',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResult', @StoredProcedureName = 'staging.LoadDataQualityValidationResult',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_ExternalFiles_and_GoldZone',@SystemName = 'UAT_ExternalFiles_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 60,@StageName = 'UAT_SQL Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'dataqualityassessment_loadmetadatadb_dataqualityvalidationresultdetail',@JobIsActive = 1,@JobOrder = 20,@TableName = 'goldprotected.vdataqualityvalidationresultdetail',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResultDetail', @StoredProcedureName = 'staging.LoadDataQualityValidationResultDetail',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_SQL Data Quality Assessment Load to Metadata DB';
GO
/************************************************************************************/
-- UAT_ML Hydration
/************************************************************************************/
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'bogus' AS ParameterName, 'bogus' AS ParameterValue --at least 1 parameter is required, this is meaningless
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_Teardown', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_ML_Teardown_daily', @StageIsActive = 1, @StageOrder = 10,  @JobName = 'UAT_ML_Teardown', @JobIsActive = 1, @JobOrder = 10, @Parameters=@Parameters, @NotebookPath = '../Data Quality Rules Engine/UAT_ML_Teardown';
GO 
EXEC [dbo].[HydrateEDANotebook] @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_EDA', @SystemSecretScope = 'internal', @SystemOrder = 20, @SystemIsActive = 1, @StageName = 'UAT_ML_EDA_Daily', @StageIsActive = 1, @StageOrder = 10,@JobName = 'UAT_ML_EDA_sandbox_bikesharingml_dataprofiling_custom', @JobIsActive = 1, @JobOrder = 10,@TableName = 'sandbox.bikesharingml', @DeltaHistoryMinutes = '-1', @SamplePercent = '-1', @ColumnToAnalyze = '', @ColumnToAnalyze2 = '',@NotebookPath = '../Exploratory Data Analysis/Data Profiling - Custom';
EXEC [dbo].[HydrateEDANotebook] @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_EDA', @SystemSecretScope = 'internal', @SystemOrder = 20, @SystemIsActive = 1, @StageName = 'UAT_ML_EDA_Daily', @StageIsActive = 1, @StageOrder = 10,@JobName = 'UAT_ML_EDA_sandbox_bikesharingml_dataprofiling_custom_univariate', @JobIsActive = 1, @JobOrder = 10,@TableName = 'sandbox.bikesharingml', @DeltaHistoryMinutes = '-1', @SamplePercent = '-1', @ColumnToAnalyze = 'temp', @ColumnToAnalyze2 = '',@NotebookPath = '../Exploratory Data Analysis/Data Profiling - Custom Univariate';
EXEC [dbo].[HydrateEDANotebook] @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_EDA', @SystemSecretScope = 'internal', @SystemOrder = 20, @SystemIsActive = 1, @StageName = 'UAT_ML_EDA_Daily', @StageIsActive = 1, @StageOrder = 10,@JobName = 'UAT_ML_EDA_sandbox_bikesharingml_dataprofiling_custom_bivariate', @JobIsActive = 1, @JobOrder = 10,@TableName = 'sandbox.bikesharingml', @DeltaHistoryMinutes = '-1', @SamplePercent = '-1', @ColumnToAnalyze = 'temp', @ColumnToAnalyze2 = 'cnt',@NotebookPath = '../Exploratory Data Analysis/Data Profiling - Custom Bivariate';
EXEC [dbo].[HydrateEDANotebook] @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_EDA', @SystemSecretScope = 'internal', @SystemOrder = 20, @SystemIsActive = 1, @StageName = 'UAT_ML_EDA_Daily', @StageIsActive = 1, @StageOrder = 10,@JobName = 'UAT_ML_EDA_sandbox_bikesharingml_dataprofiling_dataprep', @JobIsActive = 1, @JobOrder = 10,@TableName = 'sandbox.bikesharingml', @DeltaHistoryMinutes = '-1', @SamplePercent = '-1', @ColumnToAnalyze = '', @ColumnToAnalyze2 = '',@NotebookPath = '../Exploratory Data Analysis/Data Profiling - DataPrep';
EXEC [dbo].[HydrateEDANotebook] @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_EDA', @SystemSecretScope = 'internal', @SystemOrder = 20, @SystemIsActive = 1, @StageName = 'UAT_ML_EDA_Daily', @StageIsActive = 1, @StageOrder = 10,@JobName = 'UAT_ML_EDA_sandbox_bikesharingml_dataprofiling_dataprep_univariate', @JobIsActive = 1, @JobOrder = 10,@TableName = 'sandbox.bikesharingml', @DeltaHistoryMinutes = '-1', @SamplePercent = '-1', @ColumnToAnalyze = 'temp', @ColumnToAnalyze2 = '',@NotebookPath = '../Exploratory Data Analysis/Data Profiling - DataPrep Univariate';
EXEC [dbo].[HydrateEDANotebook] @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_EDA', @SystemSecretScope = 'internal', @SystemOrder = 20, @SystemIsActive = 1, @StageName = 'UAT_ML_EDA_Daily', @StageIsActive = 1, @StageOrder = 10,@JobName = 'UAT_ML_EDA_sandbox_bikesharingml_dataprofiling_dataprep_bivariate', @JobIsActive = 1, @JobOrder = 10,@TableName = 'sandbox.bikesharingml', @DeltaHistoryMinutes = '-1', @SamplePercent = '-1', @ColumnToAnalyze = 'temp', @ColumnToAnalyze2 = 'cnt',@NotebookPath = '../Exploratory Data Analysis/Data Profiling - DataPrep Bivariate';
EXEC [dbo].[HydrateEDANotebook] @ProjectName = 'UAT_ML', @SystemName = 'UAT_ML_EDA', @SystemSecretScope = 'internal', @SystemOrder = 20, @SystemIsActive = 1, @StageName = 'UAT_ML_EDA_Daily', @StageIsActive = 1, @StageOrder = 10,@JobName = 'UAT_ML_EDA_sandbox_adult_dataprofiling_pandas_profiling', @JobIsActive = 1, @JobOrder = 10,@TableName = 'sandbox.adult', @DeltaHistoryMinutes = '-1', @SamplePercent = '-1', @ColumnToAnalyze = '', @ColumnToAnalyze2 = '',@NotebookPath = '../Exploratory Data Analysis/Data Profiling - Pandas Profiling';
UPDATE dbo.Stage SET NumberOfThreads = 7 WHERE StageName IN ('UAT_ML_EDA_Daily');
GO
EXEC [dbo].[HydrateMLExperimentTraining] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_Train',@SystemSecretScope = 'internal',@SystemOrder = 30,@SystemIsActive = 1,@StageName = 'UAT_ML_Train_Daily',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_Train_sandbox_bikesharingml_linear_regression',@JobOrder = 10,@JobIsActive = 1,@TableName = 'sandbox.bikesharingml',@ExperimentName = 'UAT_ML Linear Regression for sandbox_bikesharingml',@ExperimentId = '',@ExcludedColumns = 'instant,dteday,temp,casual,registered',@Label = 'cnt',@ContinuousColumns = '',@RegularizationParameters = '0.1, 0.01',@PredictionColumn = 'prediction',@Folds = '2',@TrainTestSplit = '0.7, 0.3',@NotebookPath = '../ML/spark/Train Linear Regression';
EXEC [dbo].[HydrateMLExperimentTraining] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_Train',@SystemSecretScope = 'internal',@SystemOrder = 30,@SystemIsActive = 1,@StageName = 'UAT_ML_Train_Daily',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_Train_sandbox_bikesharingml_random_forest_regressor',@JobOrder = 10,@JobIsActive = 0,@TableName = 'sandbox.bikesharingml',@ExperimentName = 'UAT_ML Random Forest Regressor for sandbox_bikesharingml',@ExperimentId = '',@ExcludedColumns = 'instant,dteday,temp,casual,registered',@Label = 'cnt',@ContinuousColumns = '',@RegularizationParameters = '0.1, 0.01',@PredictionColumn = 'prediction',@Folds = '2',@TrainTestSplit = '0.7, 0.3',@NotebookPath = '../ML/spark/Train Random Forest Regressor';
EXEC [dbo].[HydrateMLExperimentTraining] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_Train',@SystemSecretScope = 'internal',@SystemOrder = 30,@SystemIsActive = 1,@StageName = 'UAT_ML_Train_Daily',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_Train_sandbox_bikesharingml_xgboost_regressor',@JobOrder = 10,@JobIsActive = 0,@TableName = 'sandbox.bikesharingml',@ExperimentName = 'UAT_ML XGBoost Regressor for sandbox_bikesharingml',@ExperimentId = '',@ExcludedColumns = 'instant,dteday,temp,casual,registered',@Label = 'cnt',@ContinuousColumns = '',@RegularizationParameters = '0.1, 0.01',@PredictionColumn = 'prediction',@Folds = '2',@TrainTestSplit = '0.7, 0.3',@NotebookPath = '../ML/spark/Train XGBoost Regressor';
EXEC [dbo].[HydrateMLExperimentTraining] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_Train',@SystemSecretScope = 'internal',@SystemOrder = 30,@SystemIsActive = 1,@StageName = 'UAT_ML_Train_Daily',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_Train_sandbox_adult_logistic_regression',@JobOrder = 10,@JobIsActive = 1,@TableName = 'sandbox.adult',@ExperimentName = 'UAT_ML Logistic Regression for sandbox_adult',@ExperimentId = '',@ExcludedColumns = '',@Label = 'income',@ContinuousColumns = '',@RegularizationParameters = '0.1, 0.01',@PredictionColumn = 'prediction',@Folds = '2',@TrainTestSplit = '0.7, 0.3',@NotebookPath = '../ML/spark/Train Logistic Regression';
UPDATE dbo.Stage SET NumberOfThreads = 7 WHERE StageName IN ('UAT_ML_Train_Daily');
GO
EXEC [dbo].[HydrateMLBatchInference] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_Predict',@SystemSecretScope = 'internal',@SystemOrder = 40,@SystemIsActive = 1,@StageName = 'UAT_ML_Predict_Daily',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_Predict_sandbox_bikesharingml_batch_inference',@JobOrder = 30,@JobIsActive = 1,@ExperimentNotebookPath = '/Framework/ML/spark/Train Linear Regression',@ExperimentId = '',@MetricClause = 'metrics.avg_rmse DESC',@TableName = 'sandbox.bikesharingml',@DeltaHistoryMinutes = -1,@ExcludedColumns = 'instant,dteday,temp,casual,registered',@Partitions = '8',@PrimaryKeyColumns = '',@DestinationTableName = 'uat_bikesharingpredictions',@PartitionCol = '',@ClusterCol = 'pk',@ClusterBuckets = '50',@OptimizeWhere = '',@OptimizeZOrderBy = '',@VacuumRetentionHours = 168,@LoadType = 'Overwrite',@Destination = 'silvergeneral',@NotebookPath = '../ML/Batch Inference'
EXEC [dbo].[HydrateMLStreamingInference] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_Predict',@SystemSecretScope = 'internal',@SystemOrder = 40,@SystemIsActive = 1,@StageName = 'UAT_ML_Predict_Daily',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_Predict_sandbox_bikesharingml_streaming_inference',@JobOrder = 40,@JobIsActive = 1,@ExperimentNotebookPath = '/Framework/ML/spark/Train Linear Regression',@ExperimentId = '',@MetricClause = 'metrics.avg_rmse DESC',@TableName = 'sandbox.bikesharingml',@ExcludedColumns = 'instant,dteday,temp,casual,registered',@DestinationTableName = 'uat_bikesharingpredictionsstreaming',@Destination = 'silvergeneral',@NotebookPath = '../ML/Streaming Inference';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_ML_Predict_Daily';
GO
EXEC [dbo].[HydrateDataQualityAssessment] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_ML_DataQuality_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10 ,@JobName = 'UAT_ML_Silver_Zone_QC_dataqualityassessment_silver_uat_bikesharingpredictions'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.uat_bikesharingpredictions'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 50,@StageName = 'UAT_ML_DataQuality_Silver_Zone_QC'  ,@StageIsActive = 1  ,@StageOrder = 10 ,@JobName = 'UAT_ML_Silver_Zone_QC_dataqualityassessment_silver_uat_bikesharingpredictionsstreaming'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silvergeneral.uat_bikesharingpredictionsstreaming'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_ML_DataQuality_Silver_Zone_QC';
GO
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 60,@StageName = 'UAT_ML Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_dataqualityassessment_loadmetadatadb_dataqualityvalidationresult',@JobIsActive = 1,@JobOrder = 10,@TableName = 'goldprotected.dataqualityvalidationresult',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResult', @StoredProcedureName = 'staging.LoadDataQualityValidationResult',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_ML',@SystemName = 'UAT_ML_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 60,@StageName = 'UAT_ML Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_dataqualityassessment_loadmetadatadb_dataqualityvalidationresultdetail',@JobIsActive = 1,@JobOrder = 20,@TableName = 'goldprotected.vdataqualityvalidationresultdetail',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResultDetail', @StoredProcedureName = 'staging.LoadDataQualityValidationResultDetail',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_ML Data Quality Assessment Load to Metadata DB';
GO

/************************************************************************************/
-- UAT_Cosmos Hydration
-- note: presentation zone has a dependency upon SQL test
/************************************************************************************/
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'bogus' AS ParameterName, 'bogus' AS ParameterValue --at least 1 parameter is required, this is meaningless
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'UAT_Cosmos', @SystemName = 'UAT_Cosmos_Teardown', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_Cosmos_Teardown_daily', @StageIsActive = 1, @StageOrder = 10,  @JobName = 'UAT_Cosmos_Teardown', @JobIsActive = 1, @JobOrder = 10, @Parameters=@Parameters, @NotebookPath = '../Data Quality Rules Engine/UAT_Cosmos_Teardown';
GO 
EXEC [dbo].[HydrateCosmos]           @ProjectName = 'UAT_Cosmos', @SystemName = 'UAT_Cosmos', @SystemSecretScope = 'CosmosDB', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_Cosmos_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_Cosmos_cosmosdbingest_usecases', @JobIsActive = 1, @JobOrder = 10, @Collection = 'usecases', @PartitionColumn = '/usecaseId', @PushdownPredicate = '', @SchemaName = 'cosmosdbingest', @TableName = 'usecases', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NumPartitions = '8', @PrimaryKeyColumns = 'messages_message_messageId,anonymizedMethods_method,name',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silverprotected', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch CosmosDB', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydratePresentationZone] @ProjectName = 'UAT_Cosmos', @SystemName = "UAT_Cosmos", @SystemSecretScope = 'CosmosDB', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_Cosmos_Daily', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_Cosmos_adventureworkslt_SalesLT_Address_cdb', @JobIsActive = 1, @JobOrder = 10, @CollectionName = 'addresses', @TableName = 'silverprotected.adventureworkslt_SalesLT_Address', @IDColumn = 'AddressID', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/Cosmos DB';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName IN ('UAT_Cosmos_Daily');
GO
EXEC [dbo].[HydrateCosmos]           @ProjectName = 'UAT_Cosmos', @SystemName = 'UAT_Cosmos', @SystemSecretScope = 'CosmosDB', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_Cosmos_Daily_Rerun', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_Cosmos_cosmosdbingest_usecases_rerun', @JobIsActive = 1, @JobOrder = 10, @Collection = 'usecases', @PartitionColumn = '/usecaseId', @PushdownPredicate = '', @SchemaName = 'cosmosdbingest', @TableName = 'usecases', @SilverZonePartitionColumn = '', @SilverZoneClusterColumn = 'pk', @SilverZoneClusterBuckets = '8', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NumPartitions = '8', @PrimaryKeyColumns = 'messages_message_messageId,anonymizedMethods_method,name',@ExplodeAndFlatten = 'True',@CleanseColumnNames = 'True',@TimestampColumns = '',@TimestampFormat = 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''',@EncryptColumns = '', @LoadType = 'Merge', @Destination = 'silverprotected', @BronzeZoneNotebookPath = '../Data Engineering/Bronze Zone/Batch CosmosDB', @SilverZoneNotebookPath = '../Data Engineering/Silver Zone/Delta Load';
EXEC [dbo].[HydratePresentationZone] @ProjectName = 'UAT_Cosmos', @SystemName = "UAT_Cosmos", @SystemSecretScope = 'CosmosDB', @SystemIsActive = 1, @SystemOrder = 20, @StageName = 'UAT_Cosmos_Daily_Rerun', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_Cosmos_adventureworkslt_SalesLT_Address_cdb_rerun', @JobIsActive = 1, @JobOrder = 10, @CollectionName = 'addresses', @TableName = 'silverprotected.adventureworkslt_SalesLT_Address', @IDColumn = 'AddressID', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/Cosmos DB';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName IN ('UAT_Cosmos_Daily_Rerun');
GO
GO
EXEC [dbo].[HydrateDataQualityAssessment] @ProjectName = 'UAT_Cosmos',@SystemName = 'UAT_Cosmos_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 30,@StageName = 'UAT_Cosmos_DataQuality'  ,@StageIsActive = 1  ,@StageOrder = 10 ,@JobName = 'UAT_Cosmos_DataQuality_dataqualityassessment_silverprotected_cosmosdb_cosmosdbingest_usecases'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'silverprotected.cosmosdb_cosmosdbingest_usecases'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
EXEC [dbo].[HydrateDataQualityAssessment] @ProjectName = 'UAT_Cosmos',@SystemName = 'UAT_Cosmos_DataQuality'  ,@SystemSecretScope = 'internal'  ,@SystemIsActive = 1  ,@SystemOrder = 30,@StageName = 'UAT_Cosmos_DataQuality'  ,@StageIsActive = 1  ,@StageOrder = 10 ,@JobName = 'UAT_Cosmos_DataQuality_dataqualityassessment_bronze_cosmosdb_cosmosdbingest_usecases_staging'  ,@JobIsActive = 1  ,@JobOrder = 10,@TableName = 'bronze.cosmosdb_cosmosdbingest_usecases_staging'  ,@DeltaHistoryMinutes = -1  ,@NotebookPath = '../Data Quality Rules Engine/Data Quality Assessment';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_Cosmos_DataQuality';
GO
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_Cosmos',@SystemName = 'UAT_Cosmos_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 40,@StageName = 'UAT_Cosmos Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_dataqualityassessment_loadmetadatadb_dataqualityvalidationresult',@JobIsActive = 1,@JobOrder = 10,@TableName = 'goldprotected.dataqualityvalidationresult',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResult', @StoredProcedureName = 'staging.LoadDataQualityValidationResult',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
EXEC [dbo].[HydratePlatinumZone] @ProjectName = 'UAT_Cosmos',@SystemName = 'UAT_Cosmos_DataQuality Load',@SystemSecretScope = 'metadatadb',@SystemIsActive = 1,@SystemOrder = 40,@StageName = 'UAT_Cosmos Data Quality Assessment Load to Metadata DB',@StageIsActive = 1,@StageOrder = 10,@JobName = 'UAT_ML_dataqualityassessment_loadmetadatadb_dataqualityvalidationresultdetail',@JobIsActive = 1,@JobOrder = 20,@TableName = 'goldprotected.vdataqualityvalidationresultdetail',@DestinationSchemaName = 'staging',@DestinationTableName='DataQualityValidationResultDetail', @StoredProcedureName = 'staging.LoadDataQualityValidationResultDetail',@NumPartitions='8', @IgnoreDateToProcessFilter='true', @LoadType='overwrite', @TruncateTableInsteadOfDropAndReplace='false', @IsolationLevel='READ_COMMITTED', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/SQL Spark Connector 3';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName = 'UAT_Cosmos Data Quality Assessment Load to Metadata DB';
GO
/************************************************************************************/
-- UAT_ADX Hydration
-- note: presentation zone has a dependency upon ExternalFiles test
/************************************************************************************/
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'UAT_ADX', @SystemName = 'UAT_ADX_ConnectedVehicle', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_ADX_CV', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_ADX_cvflattened', @JobIsActive = 1, @JobOrder = 10, @ExternalSystem = 'AzureDataExplorer', @Trigger = 'Microbatch', @Interval = 10, @StopSeconds = 120, @DatabaseName = 'connectedvehicle', @TableName = 'cvflattened', @OutputTableName = 'cvflattened', @NotebookPath = '../Data Engineering/Streaming/Output to Azure Data Explorer';
EXEC [dbo].[HydratePresentationZone]  @ProjectName = 'UAT_ADX', @SystemName = 'UAT_ADX_ConnectedVehicle', @SystemSecretScope = 'AzureDataExplorer', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_ADX_CV', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_ADX_noaa_noaaapi', @JobIsActive = 1, @JobOrder = 20, @DatabaseName = 'connectedvehicle', @TableName = 'noaa_noaaapi', @PresentationZoneNotebookPath = '../Data Engineering/Presentation Zone/Azure Data Explorer';
UPDATE dbo.Stage SET NumberOfThreads = 2 WHERE StageName IN ('UAT_ADX_CV');
GO
/************************************************************************************/
-- UAT_EventHub Hydration
/************************************************************************************/
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'dataSource' AS ParameterName, 'test' AS ParameterValue
UNION
SELECT 'hashtag', 'Databricks'
UNION
SELECT 'eventHubExternalSystem', 'EventHubTwitterIngestion'
UNION
SELECT 'twitterExternalSystem', 'TwitterAPI'
UNION
SELECT 'timeoutSeconds', '60';
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'UAT_EventHub', @SystemName = 'UAT_EventHub', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_EventHub_Twitter', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_EventHub_twitter_databricks_hashtag_to_eventhub', @JobIsActive = 1, @JobOrder = 10, @Parameters=@Parameters, @NotebookPath = '../Development/Send Tweets To Event Hub';
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'UAT_EventHub', @SystemName = 'UAT_EventHub', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_EventHub_Twitter', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_EventHub_twitter_databricks_eventhub_to_datalake', @JobIsActive = 1, @JobOrder = 20, @ExternalSystem = 'EventHubTwitterIngestion', @Trigger = 'Once', @MaxEventsPerTrigger = 10000, @Offset = 0, @Interval = 60, @EventHubStartingPosition = 'fromStartOfStream', @TableName = 'databrickstweets', @Destination = 'silvergeneral', @NotebookPath = '../Data Engineering/Streaming/Ingest Event Hub';
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'UAT_EventHub', @SystemName = 'UAT_EventHub', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_EventHub_Twitter', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_EventHub_twitter_databricks_sentiment_analysis', @JobIsActive = 1, @JobOrder = 30, @ExternalSystem = 'CognitiveServices', @Trigger = 'Once', @MaxEventsPerTrigger = 10000, @Interval = 60, @TableName = 'databrickstweets', @Destination = 'silvergeneral', @ColumnName = 'Body', @OutputTableName = 'databrickstweetsscored', @NotebookPath = '../Data Engineering/Streaming/Sentiment Analysis using Azure Cognitive Services';
UPDATE dbo.Stage SET NumberOfThreads = 1 WHERE StageName IN ('UAT_EventHub_Twitter');
GO
DECLARE @Parameters Parameters;
INSERT @Parameters(ParameterName, ParameterValue)
SELECT 'eventHubExternalSystem' AS ParameterName, 'EventHubCVIngestion' AS ParameterValue
UNION
SELECT 'messageCount', '100'
UNION
SELECT 'sleepSecondsBetweenMessages', '.5';
EXEC [dbo].[HydrateGenericNotebook]   @ProjectName = 'UAT_EventHub', @SystemName = 'UAT_EventHub', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_EventHub_CV', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_EventHub_CV_to_eventhub', @JobIsActive = 1, @JobOrder = 10, @Parameters=@Parameters, @NotebookPath = '../Development/Send JSON Payload to Event Hub';
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'UAT_EventHub', @SystemName = 'UAT_EventHub', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_EventHub_CV', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_EventHub_CV_ingest_eventhub', @JobIsActive = 1, @JobOrder = 20, @ExternalSystem = 'EventHubCVIngestion', @Trigger = 'Microbatch', @MaxEventsPerTrigger = 10000, @Offset = -1, @Interval = 10, @EventHubStartingPosition = 'fromStartOfStream', @StopSeconds = 120, @TableName = 'cvpayload', @Destination = 'silvergeneral', @NotebookPath = '../Data Engineering/Streaming/Ingest Event Hub';
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'UAT_EventHub', @SystemName = 'UAT_EventHub', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_EventHub_CV', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_EventHub_CV_flatten', @JobIsActive = 1, @JobOrder = 30, @ExternalSystem = 'internal', @Trigger = 'Microbatch', @MaxEventsPerTrigger = 10000, @Offset = 0, @Interval = 10, @StopSeconds = 120, @TableName = 'cvpayload', @Destination = 'silvergeneral', @ColumnName = 'Body', @OutputTableName = 'cvflattened', @NotebookPath = '../Data Engineering/Streaming/Flatten JSON';
EXEC [dbo].[HydrateStreamingNotebook] @ProjectName = 'UAT_EventHub', @SystemName = 'UAT_EventHub', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_EventHub_CV', @StageIsActive = 1, @StageOrder = 20, @JobName = 'UAT_EventHub_CV_distribution_eventhub', @JobIsActive = 1, @JobOrder = 40, @ExternalSystem = 'EventHubCVDistribution', @Trigger = 'Microbatch', @Interval = 10, @StopSeconds = 120, @TableName = 'cvflattened', @Destination = 'silvergeneral', @NotebookPath = '../Data Engineering/Streaming/Output to Event Hub';
UPDATE dbo.Stage SET NumberOfThreads = 4 WHERE StageName IN ('UAT_EventHub_CV');
GO
/************************************************************************************/
-- UAT_Table_Maintenance Hydration
/************************************************************************************/
EXEC [dbo].[HydrateSparkTableMaintenance] @ProjectName = 'UAT_Table_Maintenance', @SystemName = 'UAT_Table_Maintenance', @SystemSecretScope = 'internal', @SystemIsActive = 1, @SystemOrder = 10, @StageName = 'UAT_Table_Maintenance', @StageIsActive = 1, @StageOrder = 10, @JobName = 'UAT_Table_Maintenance_cvpayload', @JobIsActive = 1, @JobOrder = 10, @TableName = 'cvpayload', @RunOptimize = '1', @RunVacuum = '1', @OptimizeWhere = '', @OptimizeZOrderBy = '', @VacuumRetentionHours = 168, @NotebookPath = '../Orchestration/Spark Table Maintenance';
GO
