CREATE TABLE [dbo].[JobLog]
(
	 JobLogKey BIGINT NOT NULL IDENTITY(1,1)
	,JobLogGuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_dbo_JobLog_JobLogGuid DEFAULT(NEWID())
	,StageLogGuid UNIQUEIDENTIFIER NULL
	,JobKey BIGINT NULL
	,StartDateTime DATETIME2 NOT NULL CONSTRAINT DF_dbo_JobLog_StartDateTime DEFAULT(SYSDATETIME())
	,EndDateTime DATETIME2 NULL
	,LogStatusKey TINYINT NOT NULL
	,Parameters VARCHAR(MAX) NULL
	,Context VARCHAR(MAX) NULL
	,Error VARCHAR(MAX) NULL
);
GO
ALTER TABLE dbo.JobLog ADD CONSTRAINT PK_CIX_dbo_JobLog PRIMARY KEY CLUSTERED (JobLogKey);
GO
CREATE UNIQUE NONCLUSTERED INDEX UIX_dbo_JobLog_JobLogGuid ON dbo.JobLog(JobLogGuid);
GO
CREATE NONCLUSTERED INDEX IX_dbo_JobLog_StageLogGuid ON dbo.JobLog(StageLogGuid);
GO
CREATE NONCLUSTERED INDEX IX_dbo_JobLog_JobKey ON dbo.JobLog(JobKey);
GO
CREATE NONCLUSTERED INDEX IX_dbo_JobLog_LogStatusKey ON dbo.JobLog(LogStatusKey);
GO
ALTER TABLE dbo.JobLog ADD CONSTRAINT FK_JobLog_StageLog FOREIGN KEY (StageLogGuid) REFERENCES dbo.StageLog(StageLogGuid);
GO
--ALTER TABLE dbo.JobLog ADD CONSTRAINT FK_JobLog_Job FOREIGN KEY (JobKey) REFERENCES dbo.Job(JobKey);
GO
ALTER TABLE dbo.JobLog ADD CONSTRAINT FK_JobLog_LogStatus FOREIGN KEY (LogStatusKey) REFERENCES dbo.LogStatus(LogStatusKey);
GO
