DECLARE @ProjectName VARCHAR(255) = 'Marketo_Daily';
DECLARE @SystemName VARCHAR(255) = 'Marketo_Ingest';
DECLARE @SystemOrder INT = 10;
DECLARE @StageName VARCHAR(255) = 'Marketo_Ingest_Daily';
DECLARE @StageOrder INT = 10;
DECLARE @SystemSecretScope VARCHAR(255) = 'internal';
DECLARE @SystemSecretScopeTransient VARCHAR(255) = 'marketo';
DECLARE @JobOrder INT = 10;
--*--get_programs--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_programs',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_programs()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_programs.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_programs',@PrimaryKeyColumns = '*';
--*--get_campaigns--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_campaigns',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_campaigns()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_campaigns.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_campaigns',@PrimaryKeyColumns = '*';
--*--get_channels--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_channels',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_channels()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_channels.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_channels',@PrimaryKeyColumns = '*';
--*--get_smart_campaigns--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_smart_campaigns',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_smart_campaigns()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_smart_campaigns.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_smart_campaigns',@PrimaryKeyColumns = '*';
--*--get_smart_lists--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_smart_lists',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_smart_lists()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_smart_lists.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_smart_lists',@PrimaryKeyColumns = '*';
--*--get_static_lists--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_static_lists',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_static_lists()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_static_lists.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_static_lists',@PrimaryKeyColumns = '*';
--*--get_lists--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_lists',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_lists()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_lists.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_lists',@PrimaryKeyColumns = '*';
--*--get_tag_types--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_tag_types',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_tag_types()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_tag_types.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_tag_types',@PrimaryKeyColumns = '*';
--*--bulk_export_activities--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_bulk_export_activities',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.bulk_export_activities(snb.destinationFilePath)',@DestinationFilePath = 'mnt/staging-transient/marketo/bulk_export_activities.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'bulk_export_activities',@PrimaryKeyColumns = '*';
--*--bulk_export_leads--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_bulk_export_leads',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.bulk_export_leads(snb.destinationFilePath)',@DestinationFilePath = 'mnt/staging-transient/marketo/bulk_export_leads.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'bulk_export_leads',@PrimaryKeyColumns = '*';
--*--get_activity_types--*--
EXEC dbo.HydrateBatchAPI @ProjectName = @ProjectName, @SystemName = @SystemName, @SystemSecretScope = @SystemSecretScope, @SystemOrder = @SystemOrder, @StageName = @StageName, @StageOrder = @StageOrder, @JobOrder = @JobOrder, @SystemSecretScopeTransient = @SystemSecretScopeTransient,@JobName = 'Marketo_internal_Marketo_get_activity_types',@RepoName = '/Workspace/Repos/Nintex/Feature',@ClassPath = '/Workspace/Repos/Nintex/Feature/ApplicationConfiguration/Clients/Marketo/',@ClassImportFileName = 'MarketoAPI',@InstantiateAPICall = 'api = MarketoClient(snb.ClientId, snb.ClientSecret, access_token=snb.accessToken)',@APICall = 'data = api.get_activity_types()',@DestinationFilePath = 'mnt/staging-transient/marketo/get_activity_types.json',@IsDatePartitioned = 'False',@FileExtension = 'json',@SchemaName = 'Marketo',@TableName = 'get_activity_types',@PrimaryKeyColumns = '*';
